name: Fast checks

on:
  push:
  pull_request:
    branches:
      - develop
      - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Lint Python code
      run: |
        pip install flake8-black
        find ledgerwallet/ -type f -name '*.py' -exec flake8 --max-line-length=120 '{}' '+' || echo 1

  mypy:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Mypy type checking
      run: |
        pip install mypy types-requests types-protobuf
        mypy ledgerwallet
